export const POST_FETCH_START = 'POST_FETCH_START';
export const POST_FETCH_SUCCESS = 'POST_FETCH_SUCCESS';
export const POST_FETCH_FAILURE = 'POST_FETCH_FAILURE';

export const SINGLE_POST_FETCH_START = 'SINGLE_POST_FETCH_START';
export const SINGLE_POST_FETCH_SUCCESS = 'SINGLE_POST_FETCH_SUCCESS';
export const SINGLE_POST_FETCH_FAILURE = 'SINGLE_POST_FETCH_FAILURE';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const NEW_POST_CREATE_START = 'NEW_POST_CREATE_START';
export const NEW_POST_CREATE_SUCCESS = 'NEW_POST_CREATE_SUCCESS';
export const NEW_POST_CREATE_FAILURE = 'NEW_POST_CREATE_FAILURE';
export const NEW_POST_TITLE = 'NEW_POST_TITLE';
export const NEW_POST_CONTENT = 'NEW_POST_CONTENT';

export const PAGINATION_POST_FETCH_START = 'PAGINATION_POST_FETCH_START';
export const PAGINATION_POST_FETCH_SUCCESS = 'PAGINATION_POST_FETCH_SUCCESS';
export const PAGINATION_POST_FETCH_FAILURE = 'PAGINATION_POST_FETCH_FAILURE';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';